### ISSUE TITLE
CPAProxy.podspec error

### ISSUE THREAD

**Issue by mohsinalimat** [ChatSecure/ChatSecure-iOS#315]
Hello,

when i install pod then below msg pop up in terminal

[!] No podspec found for `CPAProxy` in `Submodules/CPAProxy/CPAProxy.podspec`

**Comment by chrisballinger** [comment]
`git submodule update --init`

**Comment by xandrucea** [comment]
I have the same problem. Tried to update the specs with "git submodule update --init" there is still a problem. Its also not just a problem with CPAProxy, there are more Pods that can't be installed.

**Comment by tondkared** [comment]
chrisballinger:

This part works...
`git submodule update --init` --> pulls CPAProxy but then...

but then....
pod install --> "[!] No podspec found for `XMPPFramework` in `Submodules/XMPPFramework/XMPPFramework.podspec.json`"

what is the solution?

**Comment by psomaiya17** [comment]
@chrisballinger & @tondkared : Please provide me complete steps to use git submodule update --init as I am also getting same error.

**Comment by ashishgupta301** [comment]
I have same issues with

No podspec found for `IOCipher` in `Submodules/IOCipher/IOCipher.podspec`

**Comment by etouyang** [comment]
anyone got the idea?
**[!] No podspec found for `XMPPFramework` in `Submodules/XMPPFramework/XMPPFramework.podspec`**

**Comment by ashishgupta301** [comment]
Done 

Solve it

**Comment by thrasos** [comment]
how ashishgupta301 ?

**Comment by ashishgupta301** [comment]
Generate SSH key for MAC PC and follow given steps into git then easily install another module of chat secure.

Profile->setting->SSH keys

**Comment by Akbar-khan-shinwari** [comment]
@ashishgupta301 how did you do that, because I did everything but still failed to resolved it?
